server.port=8081
spring.application.name=msorders

# URL del microservicio de catalogo (corriendo en puerto 8082)
catalog.service.url=http://localhost:8082

# Perfil activo: 'oracle' para Oracle Cloud con la Wallet, o vacio/dev para H2 en memoria
spring.profiles.active=oracle

# --- Base de datos local (H2) de respaldo ---
spring.datasource.url=jdbc:h2:mem:ordersdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
