server.port=${PORT:8081}
spring.application.name=msorders

# URL del microservicio de catalogo (corriendo en puerto 8082)
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8082}

# Base de datos PostgreSQL nativa en AWS (EC2 / RDS)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pedidos360_orders}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
