spring.application.name=msorders

# Fíjate que al final de la URL ya estamos pasando el TNS_ADMIN, así que no necesitas variables de entorno adicionales.
# CAMBIA "C:/Oracle/Wallet" por la ruta real donde descomprimiste tus archivos.
spring.datasource.url=jdbc:oracle:thin:@pedidos360orders_tp?TNS_ADMIN=C:\Wallet360\Wallet_pedidos360orders
# Las credenciales que creamos hace un momento en la base de datos
spring.datasource.username=PEDIDOS_ORDERS
spring.datasource.password=17deAcuario#07
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# Configuración para que se creen las tablas solas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

# Catalog Microservice URL (Default)
catalog.service.url=http://localhost:8081
