# --- Perfil Oracle Cloud (activar con: spring.profiles.active=oracle) ---
spring.datasource.url=jdbc:oracle:thin:@${DB_TNS_NAME:pedidos360orders_tp}?TNS_ADMIN=${TNS_ADMIN:C:/Wallet360/Wallet_pedidos360orders}
spring.datasource.username=${DB_USER:PEDIDOS_ORDERS}
spring.datasource.password=${DB_PASSWORD:17deAcuario#07}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
